create table performance_schema.table_lock_waits_summary_by_table
(
    OBJECT_TYPE                       varchar(64)     null comment 'Since this table records waits by table, always set to TABLE.',
    OBJECT_SCHEMA                     varchar(64)     null comment 'Schema name.',
    OBJECT_NAME                       varchar(64)     null comment 'Table name.',
    COUNT_STAR                        bigint unsigned not null comment 'Number of summarized events and the sum of the x_READ and x_WRITE columns.',
    SUM_TIMER_WAIT                    bigint unsigned not null comment 'Total wait time of the summarized events that are timed.',
    MIN_TIMER_WAIT                    bigint unsigned not null comment 'Minimum wait time of the summarized events that are timed.',
    AVG_TIMER_WAIT                    bigint unsigned not null comment 'Average wait time of the summarized events that are timed.',
    MAX_TIMER_WAIT                    bigint unsigned not null comment 'Maximum wait time of the summarized events that are timed.',
    COUNT_READ                        bigint unsigned not null comment 'Number of all read operations, and the sum of the equivalent x_READ_NORMAL, x_READ_WITH_SHARED_LOCKS, x_READ_HIGH_PRIORITY and x_READ_NO_INSERT columns.',
    SUM_TIMER_READ                    bigint unsigned not null comment 'Total wait time of all read operations that are timed.',
    MIN_TIMER_READ                    bigint unsigned not null comment 'Minimum wait time of all read operations that are timed.',
    AVG_TIMER_READ                    bigint unsigned not null comment 'Average wait time of all read operations that are timed.',
    MAX_TIMER_READ                    bigint unsigned not null comment 'Maximum wait time of all read operations that are timed.',
    COUNT_WRITE                       bigint unsigned not null comment 'Number of all write operations, and the sum of the equivalent x_WRITE_ALLOW_WRITE, x_WRITE_CONCURRENT_INSERT, x_WRITE_DELAYED, x_WRITE_LOW_PRIORITY and x_WRITE_NORMAL columns.',
    SUM_TIMER_WRITE                   bigint unsigned not null comment 'Total wait time of all write operations that are timed.',
    MIN_TIMER_WRITE                   bigint unsigned not null comment 'Minimum wait time of all write operations that are timed.',
    AVG_TIMER_WRITE                   bigint unsigned not null comment 'Average wait time of all write operations that are timed.',
    MAX_TIMER_WRITE                   bigint unsigned not null comment 'Maximum wait time of all write operations that are timed.',
    COUNT_READ_NORMAL                 bigint unsigned not null comment 'Number of all internal read normal locks.',
    SUM_TIMER_READ_NORMAL             bigint unsigned not null comment 'Total wait time of all internal read normal locks that are timed.',
    MIN_TIMER_READ_NORMAL             bigint unsigned not null comment 'Minimum wait time of all internal read normal locks that are timed.',
    AVG_TIMER_READ_NORMAL             bigint unsigned not null comment 'Average wait time of all internal read normal locks that are timed.',
    MAX_TIMER_READ_NORMAL             bigint unsigned not null comment 'Maximum wait time of all internal read normal locks that are timed.',
    COUNT_READ_WITH_SHARED_LOCKS      bigint unsigned not null comment 'Number of all internal read with shared locks.',
    SUM_TIMER_READ_WITH_SHARED_LOCKS  bigint unsigned not null comment 'Total wait time of all internal read with shared locks that are timed.',
    MIN_TIMER_READ_WITH_SHARED_LOCKS  bigint unsigned not null comment 'Minimum wait time of all internal read with shared locks that are timed.',
    AVG_TIMER_READ_WITH_SHARED_LOCKS  bigint unsigned not null comment 'Average wait time of all internal read with shared locks that are timed.',
    MAX_TIMER_READ_WITH_SHARED_LOCKS  bigint unsigned not null comment 'Maximum wait time of all internal read with shared locks that are timed.',
    COUNT_READ_HIGH_PRIORITY          bigint unsigned not null comment 'Number of all internal read high priority locks.',
    SUM_TIMER_READ_HIGH_PRIORITY      bigint unsigned not null comment 'Total wait time of all internal read high priority locks that are timed.',
    MIN_TIMER_READ_HIGH_PRIORITY      bigint unsigned not null comment 'Minimum wait time of all internal read high priority locks that are timed.',
    AVG_TIMER_READ_HIGH_PRIORITY      bigint unsigned not null comment 'Average wait time of all internal read high priority locks that are timed.',
    MAX_TIMER_READ_HIGH_PRIORITY      bigint unsigned not null comment 'Maximum wait time of all internal read high priority locks that are timed.',
    COUNT_READ_NO_INSERT              bigint unsigned not null comment 'Number of all internal read no insert locks.',
    SUM_TIMER_READ_NO_INSERT          bigint unsigned not null comment 'Total wait time of all internal read no insert locks that are timed.',
    MIN_TIMER_READ_NO_INSERT          bigint unsigned not null comment 'Minimum wait time of all internal read no insert locks that are timed.',
    AVG_TIMER_READ_NO_INSERT          bigint unsigned not null comment 'Average wait time of all internal read no insert locks that are timed.',
    MAX_TIMER_READ_NO_INSERT          bigint unsigned not null comment 'Maximum wait time of all internal read no insert locks that are timed.',
    COUNT_READ_EXTERNAL               bigint unsigned not null comment 'Number of all external read locks.',
    SUM_TIMER_READ_EXTERNAL           bigint unsigned not null comment 'Total wait time of all external read locks that are timed.',
    MIN_TIMER_READ_EXTERNAL           bigint unsigned not null comment 'Minimum wait time of all external read locks that are timed.',
    AVG_TIMER_READ_EXTERNAL           bigint unsigned not null comment 'Average wait time of all external read locks that are timed.',
    MAX_TIMER_READ_EXTERNAL           bigint unsigned not null comment 'Maximum wait time of all external read locks that are timed.',
    COUNT_WRITE_ALLOW_WRITE           bigint unsigned not null comment 'Number of all internal read normal locks.',
    SUM_TIMER_WRITE_ALLOW_WRITE       bigint unsigned not null comment 'Total wait time of all internal write allow write locks that are timed.',
    MIN_TIMER_WRITE_ALLOW_WRITE       bigint unsigned not null comment 'Minimum wait time of all internal write allow write locks that are timed.',
    AVG_TIMER_WRITE_ALLOW_WRITE       bigint unsigned not null comment 'Average wait time of all internal write allow write locks that are timed.',
    MAX_TIMER_WRITE_ALLOW_WRITE       bigint unsigned not null comment 'Maximum wait time of all internal write allow write locks that are timed.',
    COUNT_WRITE_CONCURRENT_INSERT     bigint unsigned not null comment 'Number of all internal concurrent insert write locks.',
    SUM_TIMER_WRITE_CONCURRENT_INSERT bigint unsigned not null comment 'Total wait time of all internal concurrent insert write locks that are timed.',
    MIN_TIMER_WRITE_CONCURRENT_INSERT bigint unsigned not null comment 'Minimum wait time of all internal concurrent insert write locks that are timed.',
    AVG_TIMER_WRITE_CONCURRENT_INSERT bigint unsigned not null comment 'Average wait time of all internal concurrent insert write locks that are timed.',
    MAX_TIMER_WRITE_CONCURRENT_INSERT bigint unsigned not null comment 'Maximum wait time of all internal concurrent insert write locks that are timed.',
    COUNT_WRITE_DELAYED               bigint unsigned not null comment 'Number of all internal write delayed locks.',
    SUM_TIMER_WRITE_DELAYED           bigint unsigned not null comment 'Total wait time of all internal write delayed locks that are timed.',
    MIN_TIMER_WRITE_DELAYED           bigint unsigned not null comment 'Minimum wait time of all internal write delayed locks that are timed.',
    AVG_TIMER_WRITE_DELAYED           bigint unsigned not null comment 'Average wait time of all internal write delayed locks that are timed.',
    MAX_TIMER_WRITE_DELAYED           bigint unsigned not null comment 'Maximum wait time of all internal write delayed locks that are timed.',
    COUNT_WRITE_LOW_PRIORITY          bigint unsigned not null comment 'Number of all internal write low priority locks.',
    SUM_TIMER_WRITE_LOW_PRIORITY      bigint unsigned not null comment 'Total wait time of all internal write low priority locks that are timed.',
    MIN_TIMER_WRITE_LOW_PRIORITY      bigint unsigned not null comment 'Minimum wait time of all internal write low priority locks that are timed.',
    AVG_TIMER_WRITE_LOW_PRIORITY      bigint unsigned not null comment 'Average wait time of all internal write low priority locks that are timed.',
    MAX_TIMER_WRITE_LOW_PRIORITY      bigint unsigned not null comment 'Maximum wait time of all internal write low priority locks that are timed.',
    COUNT_WRITE_NORMAL                bigint unsigned not null comment 'Number of all internal write normal locks.',
    SUM_TIMER_WRITE_NORMAL            bigint unsigned not null comment 'Total wait time of all internal write normal locks that are timed.',
    MIN_TIMER_WRITE_NORMAL            bigint unsigned not null comment 'Minimum wait time of all internal write normal locks that are timed.',
    AVG_TIMER_WRITE_NORMAL            bigint unsigned not null comment 'Average wait time of all internal write normal locks that are timed.',
    MAX_TIMER_WRITE_NORMAL            bigint unsigned not null comment 'Maximum wait time of all internal write normal locks that are timed.',
    COUNT_WRITE_EXTERNAL              bigint unsigned not null comment 'Number of all external write locks.',
    SUM_TIMER_WRITE_EXTERNAL          bigint unsigned not null comment 'Total wait time of all external write locks that are timed.',
    MIN_TIMER_WRITE_EXTERNAL          bigint unsigned not null comment 'Minimum wait time of all external write locks that are timed.',
    AVG_TIMER_WRITE_EXTERNAL          bigint unsigned not null comment 'Average wait time of all external write locks that are timed.',
    MAX_TIMER_WRITE_EXTERNAL          bigint unsigned not null comment 'Maximum wait time of all external write locks that are timed.'
)
    engine = PERFORMANCE_SCHEMA;

