create table performance_schema.table_io_waits_summary_by_table
(
    OBJECT_TYPE      varchar(64)     null comment 'Since this table records waits by table, always set to TABLE.',
    OBJECT_SCHEMA    varchar(64)     null comment 'Schema name.',
    OBJECT_NAME      varchar(64)     null comment 'Table name.',
    COUNT_STAR       bigint unsigned not null comment 'Number of summarized events and the sum of the x_READ and x_WRITE columns.',
    SUM_TIMER_WAIT   bigint unsigned not null comment 'Total wait time of the summarized events that are timed.',
    MIN_TIMER_WAIT   bigint unsigned not null comment 'Minimum wait time of the summarized events that are timed.',
    AVG_TIMER_WAIT   bigint unsigned not null comment 'Average wait time of the summarized events that are timed.',
    MAX_TIMER_WAIT   bigint unsigned not null comment 'Maximum wait time of the summarized events that are timed.',
    COUNT_READ       bigint unsigned not null comment 'Number of all read operations, and the sum of the equivalent x_FETCH columns.',
    SUM_TIMER_READ   bigint unsigned not null comment 'Total wait time of all read operations that are timed.',
    MIN_TIMER_READ   bigint unsigned not null comment 'Minimum wait time of all read operations that are timed.',
    AVG_TIMER_READ   bigint unsigned not null comment 'Average wait time of all read operations that are timed.',
    MAX_TIMER_READ   bigint unsigned not null comment 'Maximum wait time of all read operations that are timed.',
    COUNT_WRITE      bigint unsigned not null comment 'Number of all write operations, and the sum of the equivalent x_INSERT, x_UPDATE and x_DELETE columns.',
    SUM_TIMER_WRITE  bigint unsigned not null comment 'Total wait time of all write operations that are timed.',
    MIN_TIMER_WRITE  bigint unsigned not null comment 'Minimum wait time of all write operations that are timed.',
    AVG_TIMER_WRITE  bigint unsigned not null comment 'Average wait time of all write operations that are timed.',
    MAX_TIMER_WRITE  bigint unsigned not null comment 'Maximum wait time of all write operations that are timed.',
    COUNT_FETCH      bigint unsigned not null comment 'Number of all fetch operations.',
    SUM_TIMER_FETCH  bigint unsigned not null comment 'Total wait time of all fetch operations that are timed.',
    MIN_TIMER_FETCH  bigint unsigned not null comment 'Minimum wait time of all fetch operations that are timed.',
    AVG_TIMER_FETCH  bigint unsigned not null comment 'Average wait time of all fetch operations that are timed.',
    MAX_TIMER_FETCH  bigint unsigned not null comment 'Maximum wait time of all fetch operations that are timed.',
    COUNT_INSERT     bigint unsigned not null comment 'Number of all insert operations.',
    SUM_TIMER_INSERT bigint unsigned not null comment 'Total wait time of all insert operations that are timed.',
    MIN_TIMER_INSERT bigint unsigned not null comment 'Minimum wait time of all insert operations that are timed.',
    AVG_TIMER_INSERT bigint unsigned not null comment 'Average wait time of all insert operations that are timed.',
    MAX_TIMER_INSERT bigint unsigned not null comment 'Maximum wait time of all insert operations that are timed.',
    COUNT_UPDATE     bigint unsigned not null comment 'Number of all update operations.',
    SUM_TIMER_UPDATE bigint unsigned not null comment 'Total wait time of all update operations that are timed.',
    MIN_TIMER_UPDATE bigint unsigned not null comment 'Minimum wait time of all update operations that are timed.',
    AVG_TIMER_UPDATE bigint unsigned not null comment 'Average wait time of all update operations that are timed.',
    MAX_TIMER_UPDATE bigint unsigned not null comment 'Maximum wait time of all update operations that are timed.',
    COUNT_DELETE     bigint unsigned not null comment 'Number of all delete operations.',
    SUM_TIMER_DELETE bigint unsigned not null comment 'Total wait time of all delete operations that are timed.',
    MIN_TIMER_DELETE bigint unsigned not null comment 'Minimum wait time of all delete operations that are timed.',
    AVG_TIMER_DELETE bigint unsigned not null comment 'Average wait time of all delete operations that are timed.',
    MAX_TIMER_DELETE bigint unsigned not null comment 'Maximum wait time of all delete operations that are timed.'
)
    engine = PERFORMANCE_SCHEMA;

